# Generated by Django 5.2.5

from django.db import migrations

CATEGORY_CHOICES = [
    ('식비', '식비'),
    ('교통/차량', '교통/차량'),
    ('문화생활', '문화생활'),
    ('마트/편의점', '마트/편의점'),
    ('패션/미용', '패션/미용'),
    ('생활용품', '생활용품'),
    ('주거/통신', '주거/통신'),
    ('건강', '건강'),
    ('교육', '교육'),
    ('경조사/회비', '경조사/회비'),
    ('부모님', '부모님'),
    ('기타', '기타'),
]

def populate_categories(apps, schema_editor):
    """
    Populates the AccountBookCategory table with the choices.
    """
    AccountBookCategory = apps.get_model('manage_account', 'AccountBookCategory')
    for category_value, _ in CATEGORY_CHOICES:
        AccountBookCategory.objects.get_or_create(cat_type=category_value)

class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]