# Generated by Django 5.2.5 on 2025-09-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0002_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_pw',
            field=models.CharField(max_length=128, verbose_name='계좌비밀번호'),
        ),
    ]
