# Generated by Django 5.2.5 on 2025-09-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0002_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbookcategory',
            name='cat_kind',
            field=models.CharField(choices=[('income', '수입'), ('expense', '지출')], default='expense', max_length=10, verbose_name='카테고리 구분'),
        ),
        migrations.AlterField(
            model_name='accountbookcategory',
            name='cat_type',
            field=models.CharField(choices=[('식비', '식비'), ('교통/차량', '교통/차량'), ('문화생활', '문화생활'), ('마트/편의점', '마트/편의점'), ('패션/미용', '패션/미용'), ('생활용품', '생활용품'), ('주거/통신', '주거/통신'), ('건강', '건강'), ('교육', '교육'), ('경조사/회비', '경조사/회비'), ('부모님', '부모님'), ('기타', '기타'), ('월급', '월급'), ('부수입', '부수입'), ('용돈', '용돈'), ('상여', '상여'), ('금융소득', '금융소득')], max_length=20, verbose_name='카테고리종류'),
        ),
    ]
