# Generated by Django 5.2.5 on 2025-09-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0003_alter_account_acc_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='잔액'),
        ),
    ]
