# Generated by Django 5.2.5

from django.db import migrations

def populate_income_categories(apps, schema_editor):
    """
    Populates the AccountBookCategory table with income categories.
    """
    AccountBookCategory = apps.get_model('manage_account', 'AccountBookCategory')
    
    income_categories = ["월급", "부수입", "용돈", "상여", "금융소득", "기타"]
    
    for category_name in income_categories:
        AccountBookCategory.objects.get_or_create(
            cat_kind='income',
            cat_type=category_name
        )

class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0003_accountbookcategory_cat_kind_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_income_categories),
    ]
