# Generated by Django 5.2.5 on 2025-09-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0002_populate_categories'),
        ('manage_account', '0003_populate_transaction_tables'),
    ]

    operations = [
    ]
