# Generated by Django 5.2.5 on 2025-09-15 04:43
# manage_account/migrations/0005_alter_transactionaccount_cpart_acc.py

from django.db import migrations, models
import django.db.models.deletion 
# ...

class Migration(migrations.Migration):

    dependencies = [
        # 이전에 만들었던 0002_..._...py 마이그레이션 이름으로 수정해야 합니다.
        # 이렇게 하면 Django는 0005를 0003보다 먼저 실행합니다.
        ('manage_account', '0002_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionaccount',
            name='cpart_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='manage_account.account'),
        ),
    ]
