# Generated by Django 5.2.5

from django.db import migrations

def populate_expense_categories(apps, schema_editor):
    """
    Populates the AccountBookCategory table with expense categories.
    """
    AccountBookCategory = apps.get_model('manage_account', 'AccountBookCategory')
    
    expense_categories = [
        "식비", "교통/차량", "문화생활", "마트/편의점", "패션/미용", 
        "생활용품", "주거/통신", "건강", "교육", "경조사/회비", "부모님", "기타"
    ]

    for category_name in expense_categories:
        AccountBookCategory.objects.get_or_create(
            cat_kind='expense',
            cat_type=category_name
        )

class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0004_populate_income_categories'),
    ]

    operations = [
        migrations.RunPython(populate_expense_categories),
    ]
