# Generated by Django 5.2.5 on 2025-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0005_populate_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncash',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='transactioncash',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='사진'),
        ),
    ]
