# Generated by Django 5.2.5 on 2025-09-16 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0006_transactioncash_memo_transactioncash_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='accountbookcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='stockaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='stockcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='transactionaccount',
            name='txn_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='거래날짜'),
        ),
        migrations.AlterField(
            model_name='transactioncash',
            name='memo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='transactioncash',
            name='use_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='사용날짜'),
        ),
    ]
