# Generated by Django 5.2.5 on 2025-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_money',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12, verbose_name='잔액'),
        ),
    ]
