# Generated by Django 5.2.5 on 2025-09-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='송금액')),
                ('transaction_type', models.CharField(choices=[('SEND', '송금'), ('RECEIVE', '입금')], max_length=10, verbose_name='거래 유형')),
                ('description', models.TextField(blank=True, null=True, verbose_name='송금 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='거래 시간')),
                ('is_success', models.BooleanField(default=True, verbose_name='성공 여부')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='manage_account.account', verbose_name='송금 계좌')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='manage_account.account', verbose_name='수신 계좌')),
            ],
            options={
                'verbose_name': '거래 내역',
                'verbose_name_plural': '거래 내역들',
                'db_table': 'transaction_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
