# Generated by Django 5.2.5 on 2025-09-12 02:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_account', '0002_populate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_bank', models.CharField(max_length=10, verbose_name='받는계좌은행')),
                ('recipient_account_number', models.CharField(max_length=50, verbose_name='받는계좌번호')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='받는분성명')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='송금액')),
                ('transfer_fee', models.PositiveIntegerField(default=0, verbose_name='송금수수료')),
                ('memo', models.CharField(blank=True, max_length=100, verbose_name='메모')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='거래고유번호')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='manage_account.account', verbose_name='송금계좌')),
            ],
            options={
                'verbose_name': '송금',
                'verbose_name_plural': '송금 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(max_length=20, verbose_name='이전상태')),
                ('status_to', models.CharField(max_length=20, verbose_name='변경상태')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('reason', models.TextField(blank=True, verbose_name='변경사유')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='transfers.transfer')),
            ],
            options={
                'verbose_name': '송금내역로그',
                'verbose_name_plural': '송금내역로그 목록',
                'ordering': ['-changed_at'],
            },
        ),
    ]
